<?php
/*
 * Author: Amirhossein Jahani | iAmir.net
 * Email: me@iamir.net
 * Mobile No: +98-9146941147
 * Last modified: 2021/05/20 Thu 03:24 PM IRDT
 * Copyright (c) 2020-2022. Powered by iAmir.net
 */

namespace iLaravel\iBook\iApp;

use iLaravel\iProduct\iApp\Extends\Product;

class Book extends Product
{
    public static $s_prefix = 'NMBK';
    public static $s_start = 900;
    public static $s_end = 26999;

    public $files = ['book_index'];

    public static $find_names = ['title', 'slug'];

    public $with_resource = ['prices' => 'Price'];
    public $with_resource_single = ['terms', 'articles', 'accessories', 'awards', 'editions', 'price_olds'];
    public $with_resource_data = ['publisher', 'size', 'cover', 'product'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        parent::saving(function (self $event) {
            /*$keys = $event->updateProduct(iLaravel::createFrom(request()));
            foreach ($keys as $key)
                unset($event->$key);*/
        });
    }

    public function publisher()
    {
        return $this->belongsTo(imodal('Publisher'));
    }

    public function size()
    {
        return $this->belongsTo(imodal('BookSize'));
    }

    public function cover()
    {
        return $this->belongsTo(imodal('BookCover'));
    }

    public function creators()
    {
        return $this->belongsToMany(imodal('BookCreator'), 'books_creators', 'book_id', 'creator_id')->withPivot(['group']);
    }

    public function authors()
    {
        return $this->creators()->wherePivot('group', 'author');
    }

    public function sounds()
    {
        return $this->belongsToMany(imodal('BookSound'), 'books_sounds', 'book_id', 'sound_id')->withPivot(['link']);
    }
    public function alerts()
    {
        return $this->hasMany(imodal('ProductAlert'), 'product_id', 'product_id');
    }

    public function electronics()
    {
        return $this->belongsToMany(imodal('BookElectronic'), 'books_electronics', 'book_id', 'electronic_id')->withPivot(['link']);
    }


    public function additionalUpdate($request = null, $additional = null, $parent = null)
    {
        $this->electronics()->detach();
        foreach ($request->electronics?:[] as $index => $item)
            $this->electronics()->attach($item['electronic_id'], ['link' => $item['link']]);
        $this->sounds()->detach();
        foreach ($request->sounds?:[] as $index => $item)
            $this->sounds()->attach($item['sound_id'], ['link' => $item['link']]);
        $this->creators()->detach();
        foreach (["author", "translator", "collector", "editor", "cover_designer"] as $index) {
            $items = [];
            foreach ($request->{"{$index}s"}?:[] as $item)
                $items[BookCreator::id($item)] = ['group' => $index];
            $this->creators()->attach($items);
        }
        parent::additionalUpdate($request, $additional, $parent);
    }
    public function rules($request, $action, $arg1 = null, $arg2 = null) {
        $arg1 = $arg1 instanceof static ? $arg1 : (is_integer($arg1) ? static::find($arg1) : (is_string($arg1) ? static::findBySerial($arg1) : $arg1));
        $rules = [];
        $additionalRules = [
            'book_index_file' => 'nullable|mimes:jpeg,jpg,png,gif,pdf|max:5120',
        ];
        switch ($action) {
            case 'store':
            case 'update':
                $rules = array_merge($rules, [
                    //'product_id' => "required|exists:products,id",
                    'publisher_id' => "required|exists:publishers,id",
                    'size_id' => "required|exists:book_sizes,id",
                    'cover_id' => "required|exists:book_covers,id",
                    'title_latin' => "nullable|string",
                    'isbn' => "nullable|string",
                    'book_id' => "nullable|string",
                    'width_per_page' => "nullable|numeric",
                    'count_page' => "nullable|numeric",
                ]);
                break;
            case 'additional':
                $rules = array_merge($additionalRules, $this->getProductRules($request, $arg1), $this->getProductRules($request, $arg1, "additional"));
                break;
        }
        return $rules;
    }

}
